apiVersion: v1
kind: Service

metadata:
  name: postgres-order
  namespace: {{ .Values.namespace }}

spec:
  clusterIP: None

  selector:
    app: postgres-order

  ports:
    - port: 5432
      targetPort: 5432

---
apiVersion: apps/v1
kind: StatefulSet

metadata:
  name: postgres-order
  namespace: {{ .Values.namespace }}

spec:
  serviceName: postgres-order

  replicas: 1

  selector:
    matchLabels:
      app: postgres-order

  template:
    metadata:
      labels:
        app: postgres-order

    spec:
      containers:
        - name: postgres

          image: postgres:16-alpine

          ports:
            - containerPort: 5432

          env:
            - name: POSTGRES_DB
              value: {{ .Values.postgres.orderdb.name }}

            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_USER

            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_PASSWORD

          volumeMounts:
            - name: postgres-storage
              mountPath: /var/lib/postgresql/data

          readinessProbe:
            exec:
              command:
                - pg_isready
                - -U
                - postgres

          livenessProbe:
            exec:
              command:
                - pg_isready
                - -U
                - postgres

  volumeClaimTemplates:
    - metadata:
        name: postgres-storage

      spec:
        accessModes:
          - ReadWriteOnce

        resources:
          requests:
            storage: {{ .Values.postgres.storage }}
