apiVersion: batch/v1
kind: Job

metadata:
  name: product-db-migration
  namespace: {{ .Release.Namespace }}
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-delete-policy": before-hook-creation

spec:
  backoffLimit: 3

  template:
    spec:
      restartPolicy: Never

      initContainers: 
        - name: wait-for-db 
          image: postgres:16-alpine 
          command: 
            - sh 
            - -c 
            - |
              until pg_isready -h postgres-product -p 5432
              do
                echo waiting for postgres
                sleep 2
              done

      containers:
        - name: migration

          image: "{{ .Values.productService.image.repository }}:{{ .Values.productService.image.tag }}"

          command:
          - sh
          - -c
          - |
            until pg_isready -h postgres-product -p 5432
            do
              echo waiting for postgres
              sleep 2
            done

          env:
            - name: DB_HOST
              value: {{ .Values.productService.database.host | quote }}

            - name: DB_PORT
              value: {{ .Values.productService.database.port | quote }}

            - name: DB_NAME
              value: {{ .Values.productService.database.name | quote }}

            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_USER

            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_PASSWORD