---
# Source: chaoscart/templates/postgres-secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: default

type: Opaque

stringData:
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: postgres123
---
# Source: chaoscart/templates/frontend.yaml
apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: default
  labels:
    app: frontend

spec:
  selector:
    app: frontend

  ports:
    - name: http
      port: 80
      targetPort: 80
---
# Source: chaoscart/templates/order-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: order-service
  namespace: default
  labels:
    app: order-service

spec:
  selector:
    app: order-service

  ports:
    - name: http
      port: 4003
      targetPort: 4003
---
# Source: chaoscart/templates/postgres-order.yaml
apiVersion: v1
kind: Service

metadata:
  name: postgres-order
  namespace: default

spec:
  clusterIP: None

  selector:
    app: postgres-order

  ports:
    - port: 5432
      targetPort: 5432
---
# Source: chaoscart/templates/postgres-product.yaml
apiVersion: v1
kind: Service

metadata:
  name: postgres-product
  namespace: default

spec:
  clusterIP: None

  selector:
    app: postgres-product

  ports:
    - port: 5432
      targetPort: 5432
---
# Source: chaoscart/templates/postgres-user.yaml
apiVersion: v1
kind: Service

metadata:
  name: postgres-user
  namespace: default

spec:
  clusterIP: None

  selector:
    app: postgres-user

  ports:
    - port: 5432
      targetPort: 5432
---
# Source: chaoscart/templates/product-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: product-service
  namespace: default
  labels:
    app: product-service

spec:
  selector:
    app: product-service

  ports:
    - name: http
      port: 4002
      targetPort: 4002
---
# Source: chaoscart/templates/user-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: user-service
  namespace: default
  labels:
    app: user-service

spec:
  selector:
    app: user-service

  ports:
    - name: http
      port: 4001
      targetPort: 4001
---
# Source: chaoscart/templates/frontend.yaml
apiVersion: apps/v1
kind: Deployment

metadata:
  name: frontend
  namespace: default

spec:
  replicas: 2

  selector:
    matchLabels:
      app: frontend

  template:
    metadata:
      labels:
        app: frontend

    spec:
      containers:
        - name: frontend

          image: "ghcr.io/devanshtyagi04/chaoscart-frontend:latest"

          imagePullPolicy: Always

          ports:
            - containerPort: 80
---
# Source: chaoscart/templates/order-service.yaml
apiVersion: apps/v1
kind: Deployment

metadata:
  name: order-service
  namespace: default

spec:
  replicas: 2

  selector:
    matchLabels:
      app: order-service

  template:
    metadata:
      labels:
        app: order-service

    spec:
      containers:
      - name: order-service

        image: "ghcr.io/devanshtyagi04/chaoscart-order-service:latest"

        imagePullPolicy: Always

        env:
        
          - name: DATABASE_URL
            value: "postgresql://postgres:postgres123@postgres-order:5432/chaoscart_orders"

          - name: DB_HOST
            value: "postgres-order"

          - name: DB_PORT
            value: "5432"

          - name: DB_NAME
            value: "chaoscart_orders"

          - name: DB_USER
            valueFrom:
              secretKeyRef:
                name: postgres-secret
                key: POSTGRES_USER

          - name: DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: postgres-secret
                key: POSTGRES_PASSWORD

        ports:
          - containerPort: 4003

        readinessProbe:
          httpGet:
            path: /health
            port: 4003
          initialDelaySeconds: 10
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3

        livenessProbe:
          httpGet:
            path: /health
            port: 4003
          initialDelaySeconds: 30
          periodSeconds: 20
          timeoutSeconds: 5
          failureThreshold: 3

        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"

          limits:
            cpu: "500m"
            memory: "512Mi"
---
# Source: chaoscart/templates/product-service.yaml
apiVersion: apps/v1
kind: Deployment

metadata:
  name: product-service
  namespace: default

spec:
  replicas: 2

  selector:
    matchLabels:
      app: product-service

  template:
    metadata:
      labels:
        app: product-service

    spec:
      containers:
      - name: product-service

        image: "ghcr.io/devanshtyagi04/chaoscart-product-service:latest"

        imagePullPolicy: Always

        env:
          - name: DATABASE_URL
            value: "postgresql://postgres:postgres123@postgres-product:5432/chaoscart_products"

          - name: DB_HOST
            value: "postgres-product"

          - name: DB_PORT
            value: "5432"

          - name: DB_NAME
            value: "chaoscart_products"

          - name: DB_USER
            valueFrom:
              secretKeyRef:
                name: postgres-secret
                key: POSTGRES_USER

          - name: DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: postgres-secret
                key: POSTGRES_PASSWORD

        ports:
          - containerPort: 4002

        readinessProbe:
          httpGet:
            path: /health
            port: 4002
          initialDelaySeconds: 10
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3

        livenessProbe:
          httpGet:
            path: /health
            port: 4002
          initialDelaySeconds: 30
          periodSeconds: 20
          timeoutSeconds: 5
          failureThreshold: 3

        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"

          limits:
            cpu: "500m"
            memory: "512Mi"
---
# Source: chaoscart/templates/user-service.yaml
apiVersion: apps/v1
kind: Deployment

metadata:
  name: user-service
  namespace: default

spec:
  replicas: 2

  selector:
    matchLabels:
      app: user-service

  template:
    metadata:
      labels:
        app: user-service


    spec:
      containers:
      - name: user-service

        image: "ghcr.io/devanshtyagi04/chaoscart-user-service:latest"

        imagePullPolicy: Always

        env:
          - name: DATABASE_URL
            value: "postgresql://postgres:postgres123@postgres-user:5432/chaoscart_users"

          - name: DB_HOST
            value: "postgres-user"

          - name: DB_PORT
            value: "5432"

          - name: DB_NAME
            value: "chaoscart_users"

          - name: DB_USER
            valueFrom:
              secretKeyRef:
                name: postgres-secret
                key: POSTGRES_USER

          - name: DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: postgres-secret
                key: POSTGRES_PASSWORD

        ports:
          - containerPort: 4001

        readinessProbe:
          httpGet:
            path: /health
            port: 4001
          initialDelaySeconds: 10
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3

        livenessProbe:
          httpGet:
            path: /health
            port: 4001
          initialDelaySeconds: 30
          periodSeconds: 20
          timeoutSeconds: 5
          failureThreshold: 3

        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"

          limits:
            cpu: "500m"
            memory: "512Mi"


---
# Source: chaoscart/templates/postgres-order.yaml
apiVersion: apps/v1
kind: StatefulSet

metadata:
  name: postgres-order
  namespace: default

spec:
  serviceName: postgres-order

  replicas: 1

  selector:
    matchLabels:
      app: postgres-order

  template:
    metadata:
      labels:
        app: postgres-order

    spec:
      containers:
        - name: postgres

          image: postgres:16-alpine

          ports:
            - containerPort: 5432

          env:
            - name: POSTGRES_DB
              value: chaoscart_orders

            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_USER

            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_PASSWORD

          volumeMounts:
            - name: postgres-storage
              mountPath: /var/lib/postgresql/data

          readinessProbe:
            exec:
              command:
                - pg_isready
                - -U
                - postgres

          livenessProbe:
            exec:
              command:
                - pg_isready
                - -U
                - postgres

  volumeClaimTemplates:
    - metadata:
        name: postgres-storage

      spec:
        accessModes:
          - ReadWriteOnce

        resources:
          requests:
            storage: 1Gi

---
# Source: chaoscart/templates/postgres-product.yaml
apiVersion: apps/v1
kind: StatefulSet

metadata:
  name: postgres-product
  namespace: default

spec:
  serviceName: postgres-product

  replicas: 1

  selector:
    matchLabels:
      app: postgres-product

  template:
    metadata:
      labels:
        app: postgres-product

    spec:
      containers:
        - name: postgres

          image: postgres:16-alpine

          ports:
            - containerPort: 5432

          env:
            - name: POSTGRES_DB
              value: chaoscart_products

            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_USER

            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_PASSWORD

          volumeMounts:
            - name: postgres-storage
              mountPath: /var/lib/postgresql/data

          readinessProbe:
            exec:
              command:
                - pg_isready
                - -U
                - postgres

          livenessProbe:
            exec:
              command:
                - pg_isready
                - -U
                - postgres

  volumeClaimTemplates:
    - metadata:
        name: postgres-storage

      spec:
        accessModes:
          - ReadWriteOnce

        resources:
          requests:
            storage: 1Gi

---
# Source: chaoscart/templates/postgres-user.yaml
apiVersion: apps/v1
kind: StatefulSet

metadata:
  name: postgres-user
  namespace: default

spec:
  serviceName: postgres-user

  replicas: 1

  selector:
    matchLabels:
      app: postgres-user

  template:
    metadata:
      labels:
        app: postgres-user

    spec:
      containers:
        - name: postgres

          image: postgres:16-alpine

          ports:
            - containerPort: 5432

          env:
            - name: POSTGRES_DB
              value: chaoscart_users

            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_USER

            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_PASSWORD

          volumeMounts:
            - name: postgres-storage
              mountPath: /var/lib/postgresql/data

          readinessProbe:
            exec:
              command:
                - pg_isready
                - -U
                - postgres

          livenessProbe:
            exec:
              command:
                - pg_isready
                - -U
                - postgres

  volumeClaimTemplates:
    - metadata:
        name: postgres-storage

      spec:
        accessModes:
          - ReadWriteOnce

        resources:
          requests:
            storage: 1Gi

---
# Source: chaoscart/templates/ingess.yaml
apiVersion: networking.k8s.io/v1
kind: Ingress

metadata:
  name: chaoscart-ingress
  namespace: default

spec:
  ingressClassName: nginx

  rules:
    - host: localhost

      http:
        paths:

          - path: /
            pathType: Prefix

            backend:
              service:
                name: frontend

                port:
                  number: 80

          - path: /api/users
            pathType: Prefix

            backend:
              service:
                name: user-service

                port:
                  number: 4001

          - path: /api/products
            pathType: Prefix

            backend:
              service:
                name: product-service

                port:
                  number: 4002

          - path: /api/orders
            pathType: Prefix

            backend:
              service:
                name: order-service

                port:
                  number: 4003
---
# Source: chaoscart/templates/order-service-monitor.yaml
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor

metadata:
  name: order-service-monitor
  namespace: monitoring

  labels:
    release: monitoring

spec:
  selector:
    matchLabels:
      app: order-service

  namespaceSelector:
    matchNames:
      - default

  endpoints:
    - port: http
      path: /metrics
      interval: 15s
---
# Source: chaoscart/templates/product-service-monitor.yaml
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor

metadata:
  name: product-service-monitor
  namespace: monitoring

  labels:
    release: monitoring

spec:
  selector:
    matchLabels:
      app: product-service

  namespaceSelector:
    matchNames:
      - default

  endpoints:
    - port: http
      path: /metrics
      interval: 15s
---
# Source: chaoscart/templates/user-service-monitor.yaml
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor

metadata:
  name: user-service-monitor
  namespace: monitoring

  labels:
    release: monitoring

spec:
  selector:
    matchLabels:
      app: user-service

  namespaceSelector:
    matchNames:
      - default

  endpoints:
    - port: http
      path: /metrics
      interval: 15s
---
# Source: chaoscart/templates/order-db-migration.yaml
apiVersion: batch/v1
kind: Job

metadata:
  name: order-db-migration
  namespace: default
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-delete-policy": before-hook-creation

spec:
  backoffLimit: 3

  template:
    spec:
      restartPolicy: Never

      initContainers: 
        - name: wait-for-db 
          image: postgres:16-alpine 
          command: 
            - sh 
            - -c 
            - |
              until pg_isready -h postgres-order -p 5432
              do
                echo waiting for postgres
                sleep 2
              done

      containers:
      - name: migration

        image: "ghcr.io/devanshtyagi04/chaoscart-order-service:latest"

        command:
          - npx
          - prisma
          - migrate
          - deploy

        env:
          - name: DATABASE_URL
            value: "postgresql://postgres:postgres123@postgres-order:5432/chaoscart_orders"

          - name: DB_HOST
            value: "postgres-order"

          - name: DB_PORT
            value: "5432"

          - name: DB_NAME
            value: "chaoscart_orders"

          - name: DB_USER
            valueFrom:
              secretKeyRef:
                name: postgres-secret
                key: POSTGRES_USER

          - name: DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: postgres-secret
                key: POSTGRES_PASSWORD
---
# Source: chaoscart/templates/product-db-migration.yaml
apiVersion: batch/v1
kind: Job

metadata:
  name: product-db-migration
  namespace: default
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-delete-policy": before-hook-creation

spec:
  backoffLimit: 3

  template:
    spec:
      restartPolicy: Never

      initContainers: 
        - name: wait-for-db 
          image: postgres:16-alpine 
          command: 
            - sh 
            - -c 
            - |
              until pg_isready -h postgres-product -p 5432
              do
                echo waiting for postgres
                sleep 2
              done

      containers:
      - name: migration

        image: "ghcr.io/devanshtyagi04/chaoscart-product-service:latest"

        command:
          - npx
          - prisma
          - migrate
          - deploy

        env:
          - name: DATABASE_URL
            value: "postgresql://postgres:postgres123@postgres-product:5432/chaoscart_products"

          - name: DB_HOST
            value: "postgres-product"

          - name: DB_PORT
            value: "5432"

          - name: DB_NAME
            value: "chaoscart_products"

          - name: DB_USER
            valueFrom:
              secretKeyRef:
                name: postgres-secret
                key: POSTGRES_USER

          - name: DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: postgres-secret
                key: POSTGRES_PASSWORD
---
# Source: chaoscart/templates/user-db-migration.yaml
apiVersion: batch/v1
kind: Job

metadata:
  name: user-db-migration
  namespace: default
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-delete-policy": before-hook-creation

spec:
  backoffLimit: 3

  template:
    spec:
      restartPolicy: Never

      initContainers: 
        - name: wait-for-db 
          image: postgres:16-alpine 
          command: 
            - sh 
            - -c 
            - |
              until pg_isready -h postgres-user -p 5432
              do
                echo waiting for postgres
                sleep 2
              done

      containers:
      - name: migration

        image: "ghcr.io/devanshtyagi04/chaoscart-user-service:latest"

        command:
          - npx
          - prisma
          - migrate
          - deploy

        env:
          - name: DATABASE_URL
            value: "postgresql://postgres:postgres123@postgres-user:5432/chaoscart_users"
            
          - name: DB_HOST
            value: "postgres-user"

          - name: DB_PORT
            value: "5432"

          - name: DB_NAME
            value: "chaoscart_users"

          - name: DB_USER
            valueFrom:
              secretKeyRef:
                name: postgres-secret
                key: POSTGRES_USER

          - name: DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: postgres-secret
                key: POSTGRES_PASSWORD
