# database-secrets.yaml

apiVersion: v1
kind: Secret
metadata:
  name: database-urls
  namespace: chaoscart
type: Opaque
stringData:

  USER_DATABASE_URL: "postgresql://postgres:password@postgres-user:5432/chaoscart_users?schema=public"

  PRODUCT_DATABASE_URL: "postgresql://postgres:password@postgres-product:5432/chaoscart_products?schema=public"

  ORDER_DATABASE_URL: "postgresql://postgres:password@postgres-order:5432/chaoscart_orders?schema=public"