# order-migration-job.yaml

apiVersion: batch/v1
kind: Job
metadata:
  name: order-db-migration
  namespace: chaoscart

spec:
  backoffLimit: 3

  template:
    spec:

      restartPolicy: Never

      containers:
      - name: migration

        image: ghcr.io/devanshtyagi04/chaoscart-order-service:latest

        command:
          - sh
          - -c
          - |
            npx prisma migrate deploy

        env:
          - name: DATABASE_URL
            valueFrom:
              secretKeyRef:
                name: database-urls
                key: ORDER_DATABASE_URL